apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "praetor.fullname" . }}-consumer
  labels:
    {{- include "praetor.labels" . | nindent 4 }}
    app.kubernetes.io/component: consumer
spec:
  replicas: {{ .Values.consumer.replicas }}
  {{- with .Values.deploymentStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "praetor.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: consumer
  template:
    metadata:
      labels:
        {{- include "praetor.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: consumer
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.consumer.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "praetor.serviceAccountName" . }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- include "praetor.waitForMigrations" . | nindent 8 }}
      containers:
        - name: consumer
          image: {{ include "praetor.image" (dict "root" . "svc" "consumer") }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "praetor.configMapName" . }}
            - secretRef:
                name: {{ include "praetor.secretName" . }}
          {{- with .Values.consumer.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.consumer.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
