apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "praetor.fullname" . }}-ingestion
  labels:
    {{- include "praetor.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingestion
spec:
  replicas: {{ .Values.ingestion.replicas }}
  {{- with .Values.deploymentStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "praetor.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ingestion
  template:
    metadata:
      labels:
        {{- include "praetor.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ingestion
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.ingestion.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "praetor.serviceAccountName" . }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- include "praetor.waitForMigrations" . | nindent 8 }}
      containers:
        - name: ingestion
          image: {{ include "praetor.image" (dict "root" . "svc" "ingestion") }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ingestion.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "praetor.configMapName" . }}
            - secretRef:
                name: {{ include "praetor.secretName" . }}
          {{- with .Values.ingestion.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          {{- with .Values.ingestion.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "praetor.fullname" . }}-ingestion
  labels:
    {{- include "praetor.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingestion
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.ingestion.service.port }}
      targetPort: http
  selector:
    {{- include "praetor.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ingestion
